# Ubuntu version
os: linux
dist: focal

# Language used to develop the application                                                                                                                                                       
language: python                                                                                                                                                                                         

# Version that the application supports                                                                                                                                                                        
python:                                                                                                                                                                                                  
  - "3.8"                                                                                                                                                                                              

# Installation of Modules that are required for the Application                                                                                                                                           
install:                                                                                                                                                                                                 
  - pip install flask pytest

# Defines the Test script that should run every time the code is changed                                                                                                                            
script:                                                                                                                                                                                                  
  - pytest -v test.py